// Vehicle data converted from CSV
const vehiclesData = [
    {
        id: "tesla-model-s-2024",
        name: "Tesla Model S",
        price: 89990,
        year: 2024,
        model: "Model S",
        make: "Tesla",
        condition: "new",
        image_url: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&h=400&fit=crop",
        url: "https://ansysy24.github.io/pixeltest.github.io/car1.html",
        vin: "1HGBH41JXMN109186",
        trim: "Plaid",
        vehicle_type: "sedan",
        description: "The Tesla Model S is a full-size electric luxury sedan that redefines what an electric vehicle can be. With its sleek design, cutting-edge technology, and impressive performance, it represents the future of automotive engineering.",
        address: "123 Main Street Los Angeles CA 90210",
        exterior_color: "White",
        mileage_unit: "MI",
        mileage_value: 15000,
        tags: ["luxury", "electric", "performance", "autopilot"],
        specs: {
            engine: "Electric Motor",
            power: "670 HP",
            acceleration: "2.1 seconds",
            range: "405 miles",
            topSpeed: "200 mph"
        }
    },
    {
        id: "bmw-m3-2024",
        name: "BMW M3",
        price: 72800,
        year: 2024,
        model: "M3",
        make: "BMW",
        condition: "new",
        image_url: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=400&fit=crop",
        url: "https://ansysy24.github.io/pixeltest.github.io/car2.html",
        vin: "1HGBH41JXMN109187",
        trim: "Competition",
        vehicle_type: "sedan",
        description: "The BMW M3 is the ultimate expression of BMW's motorsport heritage in a road-going sedan. With its high-revving inline-six engine, precise handling, and aggressive styling, it delivers an exhilarating driving experience that few cars can match.",
        address: "456 Oak Avenue Beverly Hills CA 90210",
        exterior_color: "Alpine White",
        mileage_unit: "MI",
        mileage_value: 8500,
        tags: ["performance", "sports", "manual", "track-ready"],
        specs: {
            engine: "3.0L Twin-Turbo I6",
            power: "473 HP",
            acceleration: "3.9 seconds",
            range: "N/A",
            topSpeed: "155 mph"
        }
    },
    {
        id: "mercedes-amg-gt-2024",
        name: "Mercedes AMG GT",
        price: 115900,
        year: 2024,
        model: "AMG GT",
        make: "Mercedes-Benz",
        condition: "new",
        image_url: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=400&fit=crop",
        url: "https://ansysy24.github.io/pixeltest.github.io/car3.html",
        vin: "1HGBH41JXMN109188",
        trim: "GT",
        vehicle_type: "coupe",
        description: "The Mercedes-AMG GT represents the pinnacle of Mercedes-Benz performance and luxury. With its handcrafted AMG V8 engine, stunning design, and cutting-edge technology, it delivers an unforgettable driving experience that combines power with elegance.",
        address: "789 Sunset Boulevard West Hollywood CA 90069",
        exterior_color: "Obsidian Black",
        mileage_unit: "MI",
        mileage_value: 12000,
        tags: ["luxury", "performance", "handcrafted", "v8"],
        specs: {
            engine: "4.0L Twin-Turbo V8",
            power: "469 HP",
            acceleration: "4.0 seconds",
            range: "N/A",
            topSpeed: "189 mph"
        }
    },
    {
        id: "audi-r8-2024",
        name: "Audi R8",
        price: 142700,
        year: 2024,
        model: "R8",
        make: "Audi",
        condition: "new",
        image_url: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=400&fit=crop",
        url: "https://ansysy24.github.io/pixeltest.github.io/car4.html",
        vin: "1HGBH41JXMN109189",
        trim: "Performance",
        vehicle_type: "supercar",
        description: "The Audi R8 is a mid-engine supercar that brings Formula 1 technology to the road. With its naturally aspirated V10 engine, quattro all-wheel drive, and striking design, it delivers an exhilarating driving experience that combines performance with everyday usability.",
        address: "321 Rodeo Drive Beverly Hills CA 90210",
        exterior_color: "Daytona Gray",
        mileage_unit: "MI",
        mileage_value: 6800,
        tags: ["supercar", "v10", "quattro", "formula1"],
        specs: {
            engine: "5.2L V10",
            power: "562 HP",
            acceleration: "3.2 seconds",
            range: "N/A",
            topSpeed: "205 mph"
        }
    },
    {
        id: "porsche-911-2024",
        name: "Porsche 911",
        price: 101200,
        year: 2024,
        model: "911",
        make: "Porsche",
        condition: "new",
        image_url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=400&fit=crop",
        url: "https://ansysy24.github.io/pixeltest.github.io/car5.html",
        vin: "1HGBH41JXMN109190",
        trim: "Carrera",
        vehicle_type: "sports car",
        description: "The Porsche 911 is an automotive icon that has defined the sports car segment for over five decades. With its rear-engine layout, timeless design, and exceptional driving dynamics, it represents the perfect balance of performance, comfort, and everyday usability.",
        address: "654 Pacific Coast Highway Malibu CA 90265",
        exterior_color: "Guards Red",
        mileage_unit: "MI",
        mileage_value: 9200,
        tags: ["iconic", "sports", "rear-engine", "timeless"],
        specs: {
            engine: "3.0L Twin-Turbo H6",
            power: "379 HP",
            acceleration: "4.2 seconds",
            range: "N/A",
            topSpeed: "182 mph"
        }
    }
];
